# Tensors

In [162]:
import torch

- A tensor can have a single value or value with multiple dimensions.
- An easy way of finding the dimensions of a tensor is basically counting the number of square brackets at the start.
- The term tensor is so general. With a tensor many values with many dimensions can be represented.
- Everything under this is also a tensor just with special names.

- Default dtype of a tensor is float32

A scalar means, has only one value.

In [163]:
# creating a scalar value
scalar = torch.tensor(77)
scalar

tensor(77)

In [164]:
print(f"A scalar value has only a magnitude like {scalar.item()} and has no directlion. Hence a scalar value is {scalar.ndim} dimensional.")

A scalar value has only a magnitude like 77 and has no directlion. Hence a scalar value is 0 dimensional.


A vector means has arbitrary values in single dimension.

In [165]:
vector = torch.tensor([0, 2, 4, 6])
vector

tensor([0, 2, 4, 6])

In [166]:
# The term vector is used for an auto growing array in programming generally.
# In physics a vector is a structure representing a magnitude and a direction.
# In above, a row vector has created.
print(f"""
Dimensions of vector: {vector.ndim}
Size of the vector: {vector.shape}
The vector has {vector.shape[0]} elements.
""")


Dimensions of vector: 1
Size of the vector: torch.Size([4])
The vector has 4 elements.



A matrix has at least 2 dimensions like a table.

In [167]:
matrix2D = torch.tensor([[1, 2],
                         [3, 4]])
matrix2D

tensor([[1, 2],
        [3, 4]])

In [168]:
matrix2D.ndim

2

In [169]:
matrix2D.shape

torch.Size([2, 2])

Matrix of matrices are called a tensor.

In [170]:
tensor = torch.tensor([[[10, 11],
                        [12, 13],
                        [14, 15],]])
tensor

tensor([[[10, 11],
         [12, 13],
         [14, 15]]])

In [171]:
tensor.ndim

3

In [172]:
tensor.shape

torch.Size([1, 3, 2])

In [173]:
tensor[0]

tensor([[10, 11],
        [12, 13],
        [14, 15]])

In [174]:
# Will give error because only one table is initialized.
# Think it about like rubix cube.
try:
    tensor[1]
except Exception as e:
    print("Error: ", e)

Error:  index 1 is out of bounds for dimension 0 with size 1


![uninitialized_tensor.png](resources/uninitialized_tensor.png)

In [175]:
tensor = torch.tensor([[[10, 11],
                        [12, 13],
                        [14, 15],],
                       [[20, 21],
                        [22, 23],
                        [24, 25],]])
tensor

tensor([[[10, 11],
         [12, 13],
         [14, 15]],

        [[20, 21],
         [22, 23],
         [24, 25]]])

In [176]:
print(f"""
new ndim: {tensor.ndim}
new shape {tensor.shape}
""")


new ndim: 3
new shape torch.Size([2, 3, 2])



In [177]:
tensor[1]

tensor([[20, 21],
        [22, 23],
        [24, 25]])

In [178]:
# Tensors must have matching dimensions.
try:

    jagged_tensor = torch.tensor([[1, 2],

                                  [3]])

except Exception as e:
    print("Error: ", e)

Error:  expected sequence of length 2 at dim 1 (got 1)


## Random Tensors

In [179]:
random_tensor = torch.rand(size=(3,2))
random_tensor

tensor([[0.0150, 0.2086],
        [0.1634, 0.2820],
        [0.2849, 0.1131]])

In [180]:
random_tensor.shape

torch.Size([3, 2])

## Tensor of Zeros

In [181]:
zeros_tensor = torch.zeros(size=(5, 5))
zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## Tensor of Ones

In [182]:
ones_tensor = torch.ones(size=(2, 2))
ones_tensor

tensor([[1., 1.],
        [1., 1.]])

## Creating a Tensor in Range

In [183]:
# Start inclusive, end exclusive: [start, end)
range_tensor = torch.arange(start=1, end=10)
range_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
even_tensor = torch.arange(start=0, end=10, step=2)
even_tensor

tensor([0, 2, 4, 6, 8])

In [185]:
# Creates a tensor in the same shape of input tensor
zeros_like_tensor = torch.zeros_like(input=range_tensor)
zeros_like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

## Important Tensor Parameters

1. [Tensor dtype](https://pytorch.org/docs/stable/tensors.html#data-types) (eg. float32 - single precision, float16 - half precision)
2. Tensor device (CPU or GPU)
3. Tensor gradient (should pytorch watch the values inside)

---

- The default dtype is float32 but if not specified dtype will be automatically inferred. If all data is integer values, dtype will be int64.

- If an operation performed between a tensor lives in GPU and other in memory (RAM), an error will occur.

- If tensor shapes do not match for different operations' requirements, an error will occur.

In [186]:
torch.get_default_dtype()

torch.float32

In [187]:
params_tensor = torch.tensor(data=[1, 9, 0, 3],
                             dtype=None,
                             device=None,
                             requires_grad=False)
params_tensor

tensor([1, 9, 0, 3])

In [188]:
params_tensor.dtype

torch.int64

In [189]:
float32_tensor = torch.tensor(data=[1, 9, 0, 3],
                              dtype=torch.float32)
float32_tensor

tensor([1., 9., 0., 3.])

In [190]:
float32_tensor.dtype

torch.float32

In [191]:
if float32_tensor.is_cuda:
    print("Tensor living peacefully in GPU.")
else:
    print("Tensor is neighbour with OS.")

Tensor is neighbour with OS.


In [192]:
float16_tensor = torch.tensor(data=[1, 9, 0, 3],
                              dtype=torch.float16)
float16_tensor

tensor([1., 9., 0., 3.], dtype=torch.float16)

No errors? Huh...

In [193]:
result = float16_tensor * float32_tensor

In [194]:
result.dtype

torch.float32

In [195]:
result.data

tensor([ 1., 81.,  0.,  9.])

## Tensor Manipulation

- Supported basic operations like adding, subtracting, element-wise multiplying, division and matrix multiplication.
- Besides matrix multipilcation with dot product, all operations made element-wise.
- Operations return a new tensor. Original tensor is not touched.

- Normal operands are accepted. But PyTorch also has built-in methods for tensor operations.
- Operations can be made with constants or tensors.

In [196]:
op_tensor = torch.tensor([1, 2, 3])

In [197]:
op_tensor + 5

tensor([6, 7, 8])

In [198]:
op_tensor - 10

tensor([-9, -8, -7])

In [199]:
op_tensor * 8

tensor([ 8, 16, 24])

In [200]:
op_tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [201]:
torch.add(op_tensor, 5)

tensor([6, 7, 8])

In [202]:
torch.sub(op_tensor, 10)

tensor([-9, -8, -7])

In [203]:
torch.mul(op_tensor, 8)

tensor([ 8, 16, 24])

In [204]:
torch.div(op_tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

In [205]:
# Another tensor
tensor_A = torch.tensor([0, 2, 4])
tensor_B = torch.tensor([1, 3, 5])

torch.div(tensor_A, tensor_B)  # tensor([0, 6, 20])

tensor([0.0000, 0.6667, 0.8000])

## Matrix Multiplication
Rules:
1. Inner dimensions should be the same.

`(5, 2) @ (3, 12)` -> won't work

`(5, 2) @ (2, 12)` -> will work

2. Multiplication result will have the shape of outer dimensions.

`(5,2) @ (2, 12)` -> `(5, 12)`

In [206]:
matmul_tensor = torch.rand(1000)

In [207]:
%%time
val = 0
for i in range(len(matmul_tensor)):
    val += matmul_tensor[i] * matmul_tensor[i]

print(val)

tensor(310.2799)
CPU times: total: 15.6 ms
Wall time: 31 ms


In [208]:
%%time
print(torch.matmul(matmul_tensor, matmul_tensor))

tensor(310.2800)
CPU times: total: 0 ns
Wall time: 2 ms


In [209]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

try:
    torch.matmul(tensor_A, tensor_B)
except Exception as e:
    print(e)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [210]:
new_tensor_B = torch.tensor([[7, 8, 9],
                             [10, 11, 12]])

torch.matmul(tensor_A, new_tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Transpose of a Matrix

In [211]:
print(tensor_B.T)
print("tensor_B shape:", tensor_B.T.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor_B shape: torch.Size([2, 3])


In [212]:
print(f"""
Tensor shape of A: {tensor_A.shape}
Tensor shape of B: {tensor_B.shape}
Tensor shape of transposed A: {tensor_A.T.shape} 
Tensor shape of transposed B: {tensor_B.T.shape}
Tensor shape of A and B matrix multiplied {torch.matmul(tensor_A, tensor_B.T).shape}
""")


Tensor shape of A: torch.Size([3, 2])
Tensor shape of B: torch.Size([3, 2])
Tensor shape of transposed A: torch.Size([2, 3]) 
Tensor shape of transposed B: torch.Size([2, 3])
Tensor shape of A and B matrix multiplied torch.Size([3, 3])



In [213]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor Aggregation

- Finding the min, max, mean, sum...

In [214]:
agg_tensor = torch.arange(1, 10)
agg_tensor, agg_tensor.dtype


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

### Min

In [215]:
# Either use tensor function directly or use torch function and pass the tensor
agg_tensor.min(), torch.min(agg_tensor)

(tensor(1), tensor(1))

### Max

In [216]:
agg_tensor.max(), torch.max(agg_tensor)

(tensor(9), tensor(9))

### Mean

In [217]:
# Mean excepts a float or complex number input
# https://pytorch.org/docs/stable/generated/torch.mean.html
try:
    agg_tensor.mean()
except Exception as e:
    print(e)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [218]:
# Either use optional dtype parameter to specify both dtype of returned tensor
# and cast input tensor before operation
print("With tensor method: ", agg_tensor.mean(dtype=torch.float32))

# Or cast it before using if not sure.
print("With tensor method but input casted before:", 
      agg_tensor.type(torch.float32).mean())

# Similar to min and max, mean can be calculated with torch methods.
# Beware that input tensor still needed to be casted to suppoted dtype.
print("With torch methods: ", torch.mean(agg_tensor.type(torch.float32)))

With tensor method:  tensor(5.)
With tensor method but input casted before: tensor(5.)
With torch methods:  tensor(5.)


### Sum

In [219]:
agg_tensor.sum(), torch.sum(agg_tensor)

(tensor(45), tensor(45))

### Arg Min

Index of minimum element

In [220]:
agg_tensor.argmin(), torch.argmin(agg_tensor)

(tensor(0), tensor(0))

In [221]:
# Totally unnecessary but here it is anyway.
print(f"""
Minimum value in tensor is {agg_tensor[agg_tensor.argmin()]} 
and index of it is {agg_tensor.argmin()}
""")


Minimum value in tensor is 1 
and index of it is 0



Arg Max

Index of maximum element

In [222]:
agg_tensor.argmax(), torch.argmax(agg_tensor)

(tensor(8), tensor(8))

## Tensor Shape Manipulation

- Reshape: Reshape tensor to specified shape.
- View: Using the same memory return a view of the tensor.
- Stack: Stack tensor on top of each other (vertical stack) or side by side (horizonal stack). vstack and hstack also exists as seperate methods.
- Squeeze: Removes the shape of `1` dimensions from tensor.
- Unsqueeze: Adds a new dimension of `1` to specified tensor index.
- Permute: Rearrange dimension order.

In [223]:
dummy_tensor = torch.arange(1, 13)
dummy_tensor, dummy_tensor.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

### Reshape

In [224]:
# New shape must be compatible with old tensor's shape
try:
    reshaped_tensor = dummy_tensor.reshape(1, 10)
except Exception as e:
    print(e)

shape '[1, 10]' is invalid for input of size 12


In [225]:
reshaped_tensor = dummy_tensor.reshape(1, 12)
reshaped_tensor, reshaped_tensor.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

In [226]:
# It was a row vector but after reshaping turned into a column vector.
reshaped_tensor = dummy_tensor.reshape(12, 1)
reshaped_tensor, reshaped_tensor.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12]]),
 torch.Size([12, 1]))

In [227]:
reshaped_tensor = dummy_tensor.reshape(4, 3)
reshaped_tensor, reshaped_tensor.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([4, 3]))

### View

In [228]:
# See the original tensor first
print("Original tensor: ", dummy_tensor, " \n")

# Like reshape but shares the same memory
view_tensor = dummy_tensor.view(3,4)
print("View tensor: ", view_tensor)

# Alter view tensor
view_tensor[0, 0] = 99

print("+----------After altering-----------+")
# Observe that altered index changed in original tensor too
print("View tensor: ", view_tensor)
print("Original tensor: ", dummy_tensor)

# Revert original tensor to initial state for future use.
dummy_tensor = torch.arange(1, 13)

Original tensor:  tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])  

View tensor:  tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
+----------After altering-----------+
View tensor:  tensor([[99,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Original tensor:  tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


### Stack

- Tensors should be same size.

In [229]:
stacked_tensor = torch.stack([dummy_tensor, dummy_tensor], dim=0)
stacked_tensor

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [230]:
stacked_tensor = torch.stack([dummy_tensor, dummy_tensor], dim=1)
stacked_tensor

tensor([[ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10],
        [11, 11],
        [12, 12]])

In [231]:
# https://pytorch.org/docs/main/generated/torch.stack.html
# Funnily enough, website states that dim parameter has to be between 0 and 
# the number of dimensions of concatenated tensors (inclusive).
# But -1 works like 1 and -2 works like 0 because of counting backwards like python slices.
try:
    stacked_tensor = torch.stack([dummy_tensor, dummy_tensor, dummy_tensor], dim=2)
    print(stacked_tensor)
except Exception as e:
    print(e)

Dimension out of range (expected to be in range of [-2, 1], but got 2)


### hstack

- hstack method concatenates the inputs side by side depending on the written order. If row counts of tensors are equal, all's good with the world.
- If two tensors are vectors, next one will be appended to the previous tensor.

In [232]:
hstack_dummy = torch.arange(1, 5)

hstack_mat_A = torch.arange(1, 5).reshape((2,2))
hstack_mat_B = torch.arange(5, 11).reshape((2,3)) # this works
#hstack_mat_B = torch.arange(5, 11).reshape((3,2)) # this won't work

print(hstack_mat_A)
print(hstack_mat_B)

torch.hstack([hstack_mat_A, hstack_mat_B])

tensor([[1, 2],
        [3, 4]])
tensor([[ 5,  6,  7],
        [ 8,  9, 10]])


tensor([[ 1,  2,  5,  6,  7],
        [ 3,  4,  8,  9, 10]])

In [233]:
hstack_tensor_A = torch.arange(1, 9).reshape((2, 2, 2))
hstack_tensor_B = torch.arange(9, 17).reshape((2, 2, 2))

print("Tensor A:", hstack_tensor_A)
print("Tensor B:", hstack_tensor_B)

torch.hstack([hstack_tensor_A, hstack_tensor_B])

Tensor A: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Tensor B: tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])


tensor([[[ 1,  2],
         [ 3,  4],
         [ 9, 10],
         [11, 12]],

        [[ 5,  6],
         [ 7,  8],
         [13, 14],
         [15, 16]]])

![hstack_logic.png](resources/hstack_logic.png)

### vstack

This one does not have much of an appeal. Same with stack(dim=0).

In [234]:
torch.vstack([dummy_tensor, dummy_tensor])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### Squeeze

In [235]:
# It's weird...
# But if you have a tensor of shape (1, 224, 224, 3) but just (224, 224, 3) required,
# Just squeeze it.
# Also supports removing from specified dimensions using tuple or int if single dim be removed

sq_tensor = torch.zeros((2, 3, 1)) # depth, col, row
print("Unsqueezed: 2 depth, 3 columns, 1 row")
#       +---+
#      /   /|
#     +---+ |                           +---+---+---+
#    /   /| +                          /   /   /   /|
#   +---+ |/|                         +---+---+---+ |
#   |   | + |              \          |   |   |   | +
#   |   |/| +         ------\         |   |   |   |/|
#   +---+ |/|         ------/         +---+---+---+ |
#   |   | + |              /          |   |   |   | + 
#   |   |/| +                         |   |   |   |/
#   +---+ |/                          +---+---+---+
#   |   | +   
#   |   |/    
#   +---+    

print(sq_tensor)
sq_tensor.squeeze(), torch.squeeze(sq_tensor)

Unsqueezed: 2 depth, 3 columns, 1 row
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])


(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

### Unsqueeze

In [236]:
usq_tensor = torch.arange(1, 10)
usq_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
print(f"""
Shape of tensor before unsqueezing: {usq_tensor.shape}
Shape of tensor after unsqueezing for index 0: {usq_tensor.unsqueeze(dim=0).shape}
Shape of tensor after unsqueezing for index 1: {usq_tensor.unsqueeze(dim=1).shape}
""")


Shape of tensor before unsqueezing: torch.Size([9])
Shape of tensor after unsqueezing for index 0: torch.Size([1, 9])
Shape of tensor after unsqueezing for index 1: torch.Size([9, 1])



### Permute

In [238]:
#                           0    1   2
image_tensor = torch.rand((128, 128, 3))
print("Image is currently in order of width, height, color channels with the size of", image_tensor.shape)

rearranged_tensor = torch.permute(image_tensor, dims=(2, 1, 0)) # 2->0, 1->1, 0->2
print("Image rearranged as color chanels, width, height. New shape is", rearranged_tensor.shape)

Image is currently in order of width, height, color channels with the size of torch.Size([128, 128, 3])
Image rearranged as color chanels, width, height. New shape is torch.Size([3, 128, 128])


In [239]:
# Changes on assigned variable will effect original tensor since permute works as view.
print("image_tensor before changing permuted tensor:", image_tensor[0, 0, 0])
rearranged_tensor[0, 0, 0] = 1

print("image_tensor after changing permuted tensor:", image_tensor[0, 0, 0])

image_tensor before changing permuted tensor: tensor(0.4575)
image_tensor after changing permuted tensor: tensor(1.)
