# Exercises for Tensors


1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
2. Create a random tensor with shape (7, 7).
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
4. Set the random seed to 0 and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [ ]:
# ANSWER 1. Done. Eventually. Will be.

In [1]:
import torch

In [3]:
# ANSWER 2

rand7x7 = torch.rand(size=(7,7))

rand7x7, rand7x7.shape

(tensor([[0.7445, 0.2492, 0.1955, 0.3050, 0.6772, 0.7161, 0.6420],
         [0.4808, 0.8398, 0.3289, 0.5838, 0.9112, 0.2852, 0.0963],
         [0.7299, 0.1109, 0.7832, 0.0991, 0.3654, 0.6129, 0.3999],
         [0.7931, 0.5715, 0.9948, 0.5131, 0.8613, 0.1308, 0.1052],
         [0.6894, 0.0743, 0.5290, 0.5238, 0.8661, 0.4042, 0.8056],
         [0.5047, 0.3520, 0.5977, 0.9075, 0.6559, 0.1980, 0.2012],
         [0.1750, 0.6280, 0.7647, 0.2417, 0.4023, 0.7940, 0.2733]]),
 torch.Size([7, 7]))

In [5]:
# ANSWER 3
rand1x7 = torch.rand(size=(1, 7))
print(rand1x7)

# (7, 7) @ (7, 1) -> (7, 1)
matmul_result = torch.matmul(rand7x7, rand1x7.T)
matmul_result

tensor([[0.8713, 0.6587, 0.9880, 0.6775, 0.7512, 0.0994, 0.8067]])


tensor([[2.3106],
        [2.4830],
        [2.2079],
        [3.1428],
        [2.8678],
        [2.5516],
        [2.0870]])

In [17]:
# ANSWER 4

torch.manual_seed(0)
rand7x7 = torch.rand(size=(7, 7))

print("Seeded random 7x7 tensor with shape:\n", rand7x7, rand7x7.shape)

torch.manual_seed(0)
rand1x7 = torch.rand(size=(1, 7))
print("Seeded random 1x7 tensor\n", rand1x7)

# (7, 7) @ (7, 1) -> (7, 1)
matmul_result = torch.matmul(rand7x7, rand1x7.T)
print("Seeded matmul result:\n", matmul_result)

Seeded random 7x7 tensor with shape:
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) torch.Size([7, 7])
Seeded random 1x7 tensor
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
Seeded matmul result:
 tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [18]:
# ANSWER 5

# torch.cuda.manual_seed(1234)

In [20]:
# ANSWER 6

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

torch.cuda.manual_seed(1234)
gpu_tensor_A = torch.rand(size=(2,3), device=device)
torch.cuda.manual_seed(1234)
gpu_tensor_B = torch.rand(size=(2, 3), device=device)

print("Tensor A device:", gpu_tensor_A.device, "\nTensor B device:", gpu_tensor_B.device)

cuda
Tensor A device: cuda:0 
Tensor B device: cuda:0


In [22]:
# ANSWER 7

gpu_matmul_result = torch.matmul(gpu_tensor_A, gpu_tensor_B.T)

print(gpu_matmul_result)

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


In [24]:
# ANSWER 8

print("Min:", gpu_matmul_result.min())
print("Max:", gpu_matmul_result.max())

Min: tensor(0.8358, device='cuda:0')
Max: tensor(1.4578, device='cuda:0')


In [25]:
# ANSWER 9

print("Min index:", gpu_matmul_result.argmin())
print("Max index:", gpu_matmul_result.argmax())

Min index: tensor(1, device='cuda:0')
Max index: tensor(3, device='cuda:0')


In [26]:
# ANSWER 10

# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with 
# all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and print out the first tensor 
# and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)
oneoneone_tensor = torch.rand(size=(1, 1, 1, 10))

print("Tensor: ", oneoneone_tensor, "\nTensor shape: ", oneoneone_tensor.shape)

and_then_there_was_ten = torch.squeeze(oneoneone_tensor)

print("New tensor: ", and_then_there_was_ten,
      "\nNew tensor shape: ", and_then_there_was_ten.shape)

Tensor:  tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
Tensor shape:  torch.Size([1, 1, 1, 10])
New tensor:  tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) 
New tensor shape:  torch.Size([10])
