# Tensors

In [368]:
import torch

- A tensor can have a single value or value with multiple dimensions.
- An easy way of finding the dimensions of a tensor is basically counting the number of square brackets at the start.
- The term tensor is so general. With a tensor many values with many dimensions can be represented.
- Everything under this is also a tensor just with special names.

- Default dtype of a tensor is float32

A scalar means, has only one value.

In [369]:
# creating a scalar value
scalar = torch.tensor(77)
scalar

tensor(77)

In [370]:
print(f"A scalar value has only a magnitude like {scalar.item()} and has no directlion. Hence a scalar value is {scalar.ndim} dimensional.")

A scalar value has only a magnitude like 77 and has no directlion. Hence a scalar value is 0 dimensional.


A vector means has arbitrary values in single dimension.

In [371]:
vector = torch.tensor([0, 2, 4, 6])
vector

tensor([0, 2, 4, 6])

In [372]:
# The term vector is used for an auto growing array in programming generally.
# In physics a vector is a structure representing a magnitude and a direction.
# In above, a row vector has created.
print(f"""
Dimensions of vector: {vector.ndim}
Size of the vector: {vector.shape}
The vector has {vector.shape[0]} elements.
""")


Dimensions of vector: 1
Size of the vector: torch.Size([4])
The vector has 4 elements.



A matrix has at least 2 dimensions like a table.

In [373]:
matrix2D = torch.tensor([[1, 2],
                         [3, 4]])
matrix2D

tensor([[1, 2],
        [3, 4]])

In [374]:
matrix2D.ndim

2

In [375]:
matrix2D.shape

torch.Size([2, 2])

Matrix of matrices are called a tensor.

In [376]:
tensor = torch.tensor([[[10, 11],
                        [12, 13],
                        [14, 15],]])
tensor

tensor([[[10, 11],
         [12, 13],
         [14, 15]]])

In [377]:
tensor.ndim

3

In [378]:
tensor.shape

torch.Size([1, 3, 2])

In [379]:
tensor[0]

tensor([[10, 11],
        [12, 13],
        [14, 15]])

In [380]:
# Will give error because only one table is initialized.
# Think it about like rubix cube.
try:
    tensor[1]
except Exception as e:
    print("Error: ", e)

Error:  index 1 is out of bounds for dimension 0 with size 1


![uninitialized_tensor.png](resources/uninitialized_tensor.png)

In [381]:
tensor = torch.tensor([[[10, 11],
                        [12, 13],
                        [14, 15],],
                       [[20, 21],
                        [22, 23],
                        [24, 25],]])
tensor

tensor([[[10, 11],
         [12, 13],
         [14, 15]],

        [[20, 21],
         [22, 23],
         [24, 25]]])

In [382]:
print(f"""
new ndim: {tensor.ndim}
new shape {tensor.shape}
""")


new ndim: 3
new shape torch.Size([2, 3, 2])



In [383]:
tensor[1]

tensor([[20, 21],
        [22, 23],
        [24, 25]])

In [384]:
# Tensors must have matching dimensions.
try:

    jagged_tensor = torch.tensor([[1, 2],

                                  [3]])

except Exception as e:
    print("Error: ", e)

Error:  expected sequence of length 2 at dim 1 (got 1)


## Random Tensors

In [385]:
random_tensor = torch.rand(size=(3,2))
random_tensor

tensor([[0.3071, 0.1858],
        [0.2459, 0.0641],
        [0.0534, 0.8998]])

In [386]:
random_tensor.shape

torch.Size([3, 2])

## Tensor of Zeros

In [387]:
zeros_tensor = torch.zeros(size=(5, 5))
zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## Tensor of Ones

In [388]:
ones_tensor = torch.ones(size=(2, 2))
ones_tensor

tensor([[1., 1.],
        [1., 1.]])

## Creating a Tensor in Range

In [389]:
# Start inclusive, end exclusive: [start, end)
range_tensor = torch.arange(start=1, end=10)
range_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [390]:
even_tensor = torch.arange(start=0, end=10, step=2)
even_tensor

tensor([0, 2, 4, 6, 8])

In [391]:
# Creates a tensor in the same shape of input tensor
zeros_like_tensor = torch.zeros_like(input=range_tensor)
zeros_like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

## Important Tensor Parameters

1. [Tensor dtype](https://pytorch.org/docs/stable/tensors.html#data-types) (eg. float32 - single precision, float16 - half precision)
2. Tensor device (CPU or GPU)
3. Tensor gradient (should pytorch watch the values inside)

---

- The default dtype is float32 but if not specified dtype will be automatically inferred. If all data is integer values, dtype will be int64.

- If an operation performed between a tensor lives in GPU and other in memory (RAM), an error will occur.

- If tensor shapes do not match for different operations' requirements, an error will occur.

In [392]:
torch.get_default_dtype()

torch.float32

In [393]:
params_tensor = torch.tensor(data=[1, 9, 0, 3],
                             dtype=None,
                             device=None,
                             requires_grad=False)
params_tensor

tensor([1, 9, 0, 3])

In [394]:
params_tensor.dtype

torch.int64

In [395]:
float32_tensor = torch.tensor(data=[1, 9, 0, 3],
                              dtype=torch.float32)
float32_tensor

tensor([1., 9., 0., 3.])

In [396]:
float32_tensor.dtype

torch.float32

In [397]:
if float32_tensor.is_cuda:
    print("Tensor living peacefully in GPU.")
else:
    print("Tensor is neighbour with OS.")

Tensor is neighbour with OS.


In [398]:
float16_tensor = torch.tensor(data=[1, 9, 0, 3],
                              dtype=torch.float16)
float16_tensor

tensor([1., 9., 0., 3.], dtype=torch.float16)

No errors? Huh...

In [399]:
result = float16_tensor * float32_tensor

In [400]:
result.dtype

torch.float32

In [401]:
result.data

tensor([ 1., 81.,  0.,  9.])

## Tensor Manipulation

- Supported basic operations like adding, subtracting, element-wise multiplying, division and matrix multiplication.
- Besides matrix multipilcation with dot product, all operations made element-wise.
- Operations return a new tensor. Original tensor is not touched.

- Normal operands are accepted. But PyTorch also has built-in methods for tensor operations.
- Operations can be made with constants or tensors.

In [402]:
op_tensor = torch.tensor([1, 2, 3])

In [403]:
op_tensor + 5

tensor([6, 7, 8])

In [404]:
op_tensor - 10

tensor([-9, -8, -7])

In [405]:
op_tensor * 8

tensor([ 8, 16, 24])

In [406]:
op_tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [407]:
torch.add(op_tensor, 5)

tensor([6, 7, 8])

In [408]:
torch.sub(op_tensor, 10)

tensor([-9, -8, -7])

In [409]:
torch.mul(op_tensor, 8)

tensor([ 8, 16, 24])

In [410]:
torch.div(op_tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

In [411]:
# Another tensor
tensor_A = torch.tensor([0, 2, 4])
tensor_B = torch.tensor([1, 3, 5])

torch.div(tensor_A, tensor_B)  # tensor([0, 6, 20])

tensor([0.0000, 0.6667, 0.8000])

## Matrix Multiplication
Rules:
1. Inner dimensions should be the same.

`(5, 2) @ (3, 12)` -> won't work

`(5, 2) @ (2, 12)` -> will work

2. Multiplication result will have the shape of outer dimensions.

`(5,2) @ (2, 12)` -> `(5, 12)`

In [412]:
matmul_tensor = torch.rand(1000)

In [413]:
%%time
val = 0
for i in range(len(matmul_tensor)):
    val += matmul_tensor[i] * matmul_tensor[i]

print(val)

tensor(331.0392)
CPU times: total: 15.6 ms
Wall time: 25 ms


In [414]:
%%time
print(torch.matmul(matmul_tensor, matmul_tensor))

tensor(331.0391)
CPU times: total: 0 ns
Wall time: 1 ms


In [415]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

try:
    torch.matmul(tensor_A, tensor_B)
except Exception as e:
    print(e)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [416]:
new_tensor_B = torch.tensor([[7, 8, 9],
                             [10, 11, 12]])

torch.matmul(tensor_A, new_tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Transpose of a Matrix

In [417]:
print(tensor_B.T)
print("tensor_B shape:", tensor_B.T.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor_B shape: torch.Size([2, 3])


In [418]:
print(f"""
Tensor shape of A: {tensor_A.shape}
Tensor shape of B: {tensor_B.shape}
Tensor shape of transposed A: {tensor_A.T.shape} 
Tensor shape of transposed B: {tensor_B.T.shape}
Tensor shape of A and B matrix multiplied {torch.matmul(tensor_A, tensor_B.T).shape}
""")


Tensor shape of A: torch.Size([3, 2])
Tensor shape of B: torch.Size([3, 2])
Tensor shape of transposed A: torch.Size([2, 3]) 
Tensor shape of transposed B: torch.Size([2, 3])
Tensor shape of A and B matrix multiplied torch.Size([3, 3])



In [419]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor Aggregation

- Finding the min, max, mean, sum...

In [420]:
agg_tensor = torch.arange(1, 10)
agg_tensor, agg_tensor.dtype


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

### Min

In [421]:
# Either use tensor function directly or use torch function and pass the tensor
agg_tensor.min(), torch.min(agg_tensor)

(tensor(1), tensor(1))

### Max

In [422]:
agg_tensor.max(), torch.max(agg_tensor)

(tensor(9), tensor(9))

### Mean

In [423]:
# Mean excepts a float or complex number input
# https://pytorch.org/docs/stable/generated/torch.mean.html
try:
    agg_tensor.mean()
except Exception as e:
    print(e)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [424]:
# Either use optional dtype parameter to specify both dtype of returned tensor
# and cast input tensor before operation
print("With tensor method: ", agg_tensor.mean(dtype=torch.float32))

# Or cast it before using if not sure.
print("With tensor method but input casted before:", 
      agg_tensor.type(torch.float32).mean())

# Similar to min and max, mean can be calculated with torch methods.
# Beware that input tensor still needed to be casted to suppoted dtype.
print("With torch methods: ", torch.mean(agg_tensor.type(torch.float32)))

With tensor method:  tensor(5.)
With tensor method but input casted before: tensor(5.)
With torch methods:  tensor(5.)


### Sum

In [425]:
agg_tensor.sum(), torch.sum(agg_tensor)

(tensor(45), tensor(45))

### Arg Min

Index of minimum element

In [426]:
agg_tensor.argmin(), torch.argmin(agg_tensor)

(tensor(0), tensor(0))

In [427]:
# Totally unnecessary but here it is anyway.
print(f"""
Minimum value in tensor is {agg_tensor[agg_tensor.argmin()]} 
and index of it is {agg_tensor.argmin()}
""")


Minimum value in tensor is 1 
and index of it is 0



Arg Max

Index of maximum element

In [428]:
agg_tensor.argmax(), torch.argmax(agg_tensor)

(tensor(8), tensor(8))

## Tensor Shape Manipulation

- Reshape: Reshape tensor to specified shape.
- View: Using the same memory return a view of the tensor.
- Stack: Stack tensor on top of each other (vertical stack) or side by side (horizonal stack). vstack and hstack also exists as seperate methods.
- Squeeze: Removes the shape of `1` dimensions from tensor.
- Unsqueeze: Adds a new dimension of `1` to specified tensor index.
- Permute: Rearrange dimension order.

In [429]:
dummy_tensor = torch.arange(1, 13)
dummy_tensor, dummy_tensor.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

### Reshape

In [430]:
# New shape must be compatible with old tensor's shape
try:
    reshaped_tensor = dummy_tensor.reshape(1, 10)
except Exception as e:
    print(e)

shape '[1, 10]' is invalid for input of size 12


In [431]:
reshaped_tensor = dummy_tensor.reshape(1, 12)
reshaped_tensor, reshaped_tensor.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

In [432]:
# It was a row vector but after reshaping turned into a column vector.
reshaped_tensor = dummy_tensor.reshape(12, 1)
reshaped_tensor, reshaped_tensor.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12]]),
 torch.Size([12, 1]))

In [433]:
reshaped_tensor = dummy_tensor.reshape(4, 3)
reshaped_tensor, reshaped_tensor.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([4, 3]))

### View

In [434]:
# See the original tensor first
print("Original tensor: ", dummy_tensor, " \n")

# Like reshape but shares the same memory
view_tensor = dummy_tensor.view(3,4)
print("View tensor: ", view_tensor)

# Alter view tensor
view_tensor[0, 0] = 99

print("+----------After altering-----------+")
# Observe that altered index changed in original tensor too
print("View tensor: ", view_tensor)
print("Original tensor: ", dummy_tensor)

# Revert original tensor to initial state for future use.
dummy_tensor = torch.arange(1, 13)

Original tensor:  tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])  

View tensor:  tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
+----------After altering-----------+
View tensor:  tensor([[99,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Original tensor:  tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


### Stack

- Tensors should be same size.

In [435]:
stacked_tensor = torch.stack([dummy_tensor, dummy_tensor], dim=0)
stacked_tensor

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [436]:
stacked_tensor = torch.stack([dummy_tensor, dummy_tensor], dim=1)
stacked_tensor

tensor([[ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10],
        [11, 11],
        [12, 12]])

In [437]:
# https://pytorch.org/docs/main/generated/torch.stack.html
# Funnily enough, website states that dim parameter has to be between 0 and 
# the number of dimensions of concatenated tensors (inclusive).
# But -1 works like 1 and -2 works like 0 because of counting backwards like python slices.
try:
    stacked_tensor = torch.stack([dummy_tensor, dummy_tensor, dummy_tensor], dim=2)
    print(stacked_tensor)
except Exception as e:
    print(e)

Dimension out of range (expected to be in range of [-2, 1], but got 2)


### hstack

- hstack method concatenates the inputs side by side depending on the written order. If row counts of tensors are equal, all's good with the world.
- If two tensors are vectors, next one will be appended to the previous tensor.

In [438]:
hstack_dummy = torch.arange(1, 5)

hstack_mat_A = torch.arange(1, 5).reshape((2,2))
hstack_mat_B = torch.arange(5, 11).reshape((2,3)) # this works
#hstack_mat_B = torch.arange(5, 11).reshape((3,2)) # this won't work

print(hstack_mat_A)
print(hstack_mat_B)

torch.hstack([hstack_mat_A, hstack_mat_B])

tensor([[1, 2],
        [3, 4]])
tensor([[ 5,  6,  7],
        [ 8,  9, 10]])


tensor([[ 1,  2,  5,  6,  7],
        [ 3,  4,  8,  9, 10]])

In [439]:
hstack_tensor_A = torch.arange(1, 9).reshape((2, 2, 2))
hstack_tensor_B = torch.arange(9, 17).reshape((2, 2, 2))

print("Tensor A:", hstack_tensor_A)
print("Tensor B:", hstack_tensor_B)

torch.hstack([hstack_tensor_A, hstack_tensor_B])

Tensor A: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Tensor B: tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])


tensor([[[ 1,  2],
         [ 3,  4],
         [ 9, 10],
         [11, 12]],

        [[ 5,  6],
         [ 7,  8],
         [13, 14],
         [15, 16]]])

![hstack_logic.png](resources/hstack_logic.png)

### vstack

This one does not have much of an appeal. Same with stack(dim=0).

In [440]:
torch.vstack([dummy_tensor, dummy_tensor])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### Squeeze

In [441]:
# It's weird...
# But if you have a tensor of shape (1, 224, 224, 3) but just (224, 224, 3) required,
# Just squeeze it.
# Also supports removing from specified dimensions using tuple or int if single dim be removed

sq_tensor = torch.zeros((2, 3, 1)) # depth, col, row
print("Unsqueezed: 2 depth, 3 columns, 1 row")
#       +---+
#      /   /|
#     +---+ |                           +---+---+---+
#    /   /| +                          /   /   /   /|
#   +---+ |/|                         +---+---+---+ |
#   |   | + |              \          |   |   |   | +
#   |   |/| +         ------\         |   |   |   |/|
#   +---+ |/|         ------/         +---+---+---+ |
#   |   | + |              /          |   |   |   | + 
#   |   |/| +                         |   |   |   |/
#   +---+ |/                          +---+---+---+
#   |   | +   
#   |   |/    
#   +---+    

print(sq_tensor)
sq_tensor.squeeze(), torch.squeeze(sq_tensor)

Unsqueezed: 2 depth, 3 columns, 1 row
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])


(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

### Unsqueeze

In [442]:
usq_tensor = torch.arange(1, 10)
usq_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [443]:
print(f"""
Shape of tensor before unsqueezing: {usq_tensor.shape}
Shape of tensor after unsqueezing for index 0: {usq_tensor.unsqueeze(dim=0).shape}
Shape of tensor after unsqueezing for index 1: {usq_tensor.unsqueeze(dim=1).shape}
""")


Shape of tensor before unsqueezing: torch.Size([9])
Shape of tensor after unsqueezing for index 0: torch.Size([1, 9])
Shape of tensor after unsqueezing for index 1: torch.Size([9, 1])



### Permute

In [444]:
#                           0    1   2
image_tensor = torch.rand((128, 128, 3))
print("Image is currently in order of width, height, color channels with the size of", image_tensor.shape)

rearranged_tensor = torch.permute(image_tensor, dims=(2, 1, 0)) # 2->0, 1->1, 0->2
print("Image rearranged as color chanels, width, height. New shape is", rearranged_tensor.shape)

Image is currently in order of width, height, color channels with the size of torch.Size([128, 128, 3])
Image rearranged as color chanels, width, height. New shape is torch.Size([3, 128, 128])


In [445]:
# Changes on assigned variable will effect original tensor since permute works as view.
print("image_tensor before changing permuted tensor:", image_tensor[0, 0, 0])
rearranged_tensor[0, 0, 0] = 1

print("image_tensor after changing permuted tensor:", image_tensor[0, 0, 0])

image_tensor before changing permuted tensor: tensor(0.7146)
image_tensor after changing permuted tensor: tensor(1.)


## Tensor Indexing

Tensors can be sliced like python arrays. 

In [446]:
slice_tensor = torch.arange(1, 10).reshape(1, 3, 3) # same as 2d matrix layout but in 3d.

slice_tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [447]:
# Will give an error because first dimension has only rank of 1 
# and starting from 0.
try:
    slice_tensor[1]
except Exception as e:
    print(e)

index 1 is out of bounds for dimension 0 with size 1


In [448]:
# "Give me 0th dimension of all values."
slice_tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [449]:
# "Give me 0th dimension of all values."
slice_tensor[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [450]:
# "Give me first element of all dimensions"
# Utimately leads to retrieving first ever value in tensor.
slice_tensor[0, 0, 0]

tensor(1)

In [451]:
# "Give me the last element of a 3x3 tensor."
slice_tensor[0, 2, 2]

tensor(9)

In [452]:
# "Give me all values in 3rd column."
slice_tensor[0, :, 2]

tensor([3, 6, 9])

## PyTorch, Numpy and You

PyTorch does not strictly depend on [Numpy](https://numpy.org/) but they can work together. Numpy is a widely used library in deep learning because of its speed and built-in functions. Also numpy array can be saved to a file for faster read-write operations from disk.

![pytorch_and_numpy.png](resources/pytorch_and_numpy.png)

In [453]:
import torch
import numpy as np

### Numpy Array to Tensor

In [454]:
# Float array to float tensor
nparray = np.arange(1.0, 10.0)
tensor_from_np = torch.from_numpy(nparray)

nparray, tensor_from_np

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

Newly crated tensor from numpy array has dtype of float64 because numpy has default dtype of float 64. This is different than PyTorch's float32.

In [455]:
nparray.dtype

dtype('float64')

Also numpy has different default integer dtype (int32). On the other hand PyTorch using int64 for integer tensors.

In [456]:
# Int array to int tensor
nparray = np.arange(1, 10)
tensor_from_np = torch.from_numpy(nparray)

nparray, tensor_from_np

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

In [457]:
torch.arange(0, 1).dtype

torch.int64

In [458]:
# Making sure of dtypes
np_array = np.arange(10., dtype=np.float32)
np_tensor = torch.from_numpy(np_array)

np_tensor.dtype

torch.float32

[Numpy array and tensor values share the same memory](https://pytorch.org/docs/2.5/generated/torch.from_numpy.html). Changes to either of the array of the tensor will be reflected to each other. 

In [459]:
np_array[0] = 100
np_tensor[1] = 200

np_array, np_tensor

(array([100., 200.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       dtype=float32),
 tensor([100., 200.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]))

**Warning:** If dtype changed after using ndarray for tensor creation, numpy array and tensor would no longer share the same memory.

In [460]:
np_array = np.arange(10.)
np_tensor = torch.from_numpy(np_array).type(torch.float32)

np_array[0] = 100
np_tensor[1] = 200

print(np_array, np_array.dtype)
print(np_tensor, np_tensor.dtype)

[100.   1.   2.   3.   4.   5.   6.   7.   8.   9.] float64
tensor([  0., 200.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]) torch.float32


### Tensor to Numpy Array

In [463]:
soon_to_array_tensor = torch.tensor([1, 2, 3])
now_array_tensor = soon_to_array_tensor.numpy()

now_array_tensor

array([1, 2, 3], dtype=int64)

Just like pytorch infers dtype of numpy array and returns a tensor with same dtype, same applies if a tensor gets converted to a numpy array.

In [464]:
soon_to_array_tensor.dtype, now_array_tensor.dtype

(torch.int64, dtype('int64'))

What happens to `tensor->numpy` array if tensor gets manipulated? Same as `numpy->tensor` they share the same memory.

In [465]:
soon_to_array_tensor += 1

soon_to_array_tensor, now_array_tensor

(tensor([2, 3, 4]), array([2, 3, 4], dtype=int64))

## Reproducibility

- Every time a random number generating method called, a pseudorandom number generator is called.
- In order to have reproducible results across the runs a random number seed can be set.

In [467]:
import torch

rand_tensor_A = torch.rand((3,3))
rand_tensor_B = torch.rand((3,3))

print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)

tensor([[0.1395, 0.6975, 0.7881],
        [0.9431, 0.2720, 0.2562],
        [0.8427, 0.3948, 0.9350]])
tensor([[0.8776, 0.4167, 0.2465],
        [0.3616, 0.5553, 0.9127],
        [0.0781, 0.7647, 0.0883]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [476]:
torch.manual_seed(77)
rand_tensor_C = torch.rand((3, 3))
torch.manual_seed(77)
rand_tensor_D = torch.rand((3, 3))

print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.2919, 0.2857, 0.4021],
        [0.4645, 0.9503, 0.2564],
        [0.6645, 0.8609, 0.3538]])
tensor([[0.2919, 0.2857, 0.4021],
        [0.4645, 0.9503, 0.2564],
        [0.6645, 0.8609, 0.3538]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Running PyTorch on GPU

- Until this part all the tensors were stored in memory.
- This notebook written in a local machine with NVidia GPU. For using the same setup refer [here](README.md#how-did-i-installed).
- If you'll work on a cloud environment, make sure you have access to a GPU. 
- You can check the GPU in colab with `!nvidia-smi` command.

- For best practices check [here](https://pytorch.org/docs/stable/notes/cuda.html#best-practices).

### Check GPU Access

In [477]:
import torch
torch.cuda.is_available()

True

Running PyTorch device agnostic. Use GPU if available. If not use CPU for operations.

In [478]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [479]:
# For multiple GPU setups
torch.cuda.device_count()

1

### Moving Existing Tensor to GPU

In [480]:
cpu_tensor = torch.tensor([1,2,3])
cpu_tensor.device

device(type='cpu')

In [482]:
gpu_tensor = cpu_tensor.to(device)
gpu_tensor

tensor([1, 2, 3], device='cuda:0')

Some libraries can not access GPU memory to perform calculations. In that case tensor to be used should moved back to memory.

In [483]:
try:
    gpu_tensor.numpy()
except Exception as e:
    print(e)

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [488]:
welcome_back_tensor = gpu_tensor.cpu().numpy()
welcome_back_tensor

array([1, 2, 3], dtype=int64)